# Generated by Django 6.0.5 on 2026-05-31 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_entity_id', models.PositiveIntegerField()),
                ('original_entity_ct', models.ForeignKey(limit_choices_to={'model__in': ['groupement', 'laboratory', 'pharmacy', 'pharmacygroupement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SharedTreeElement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_tree_element_id', models.PositiveIntegerField()),
                ('original_tree_element_ct', models.ForeignKey(limit_choices_to={'model__in': ['treefile', 'treefolder']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tree_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_elements', to='document_tree.treeentity')),
            ],
        ),
        migrations.CreateModel(
            name='TreeFolder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tree_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='document_tree.treeentity')),
                ('tree_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='document_tree.treefolder')),
            ],
        ),
        migrations.CreateModel(
            name='TreeFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_file_id', models.PositiveIntegerField()),
                ('original_file_ct', models.ForeignKey(limit_choices_to={'model__in': ['commercialcondition', 'document', 'flyer']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tree_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='document_tree.treeentity')),
                ('tree_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='document_tree.treefolder')),
            ],
        ),
    ]
